version: '3.3'
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - ./to_do_db.sql:/docker-entrypoint-initdb.d/to_do.sql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "5000:80"
    links:
        - "db:db"
volumes:
  my-db:
